package com.asiainfo.meo.customer.device.app.model.entity;

// Generated 2015-3-11 19:56:39 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmDeviceInfoHisId generated by hbm2java
 */
public class DeviceInfoHis implements java.io.Serializable
{
    private static final long serialVersionUID = 1714712734893954233L;
    private long      deviceId;
    private String    deviceToken;
    private int       deviceType;
    private String    osVersion;
    private int       sts;
    private Timestamp createDate;
    private Timestamp modifyDate;
    private long      userId;
    private String    imei;
    
   
    
    public long getDeviceId()
    {
        return this.deviceId;
    }
    
    public void setDeviceId(long deviceId)
    {
        this.deviceId = deviceId;
    }
    
    public String getDeviceToken()
    {
        return this.deviceToken;
    }
    
    public void setDeviceToken(String deviceToken)
    {
        this.deviceToken = deviceToken;
    }
    
    public int getDeviceType()
    {
        return this.deviceType;
    }
    
    public void setDeviceType(int deviceType)
    {
        this.deviceType = deviceType;
    }
    
    public String getOsVersion()
    {
        return this.osVersion;
    }
    
    public void setOsVersion(String osVersion)
    {
        this.osVersion = osVersion;
    }
    
    public int getSts()
    {
        return this.sts;
    }
    
    public void setSts(int sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public long getUserId()
    {
        return this.userId;
    }
    
    public void setUserId(long userId)
    {
        this.userId = userId;
    }
    
    public String getImei()
    {
        return this.imei;
    }
    
    public void setImei(String imei)
    {
        this.imei = imei;
    }
   
    
}
