package com.asiainfo.meo.prm.profile.app.model.entity;

// Generated 2015-3-12 19:34:02 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmPartnerInfoHis generated by hbm2java
 */
public class PartnerInfoHis implements java.io.Serializable
{
    private static final long serialVersionUID = 650473652292586605L;
    
    private long              id;
    
    private long              partnerId;
    
    private String            companyName;
    
    private String            taxCode;
    
    private String            businessCode;
    
    private String            emailAddr;
    
    private String            msidn;
    
    private String            billAddr;
    
    private Timestamp         validDate;
    
    private Timestamp         expiredDate;
    
    private String            contactName;
    
    private String            contactMsidn;
    
    private String            contactEmail;
    
    private Long              postCode;
    
    private Integer           countryCode;
    
    private Integer           cityCode;
    
    private Integer           provinceCode;
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public long getPartnerId()
    {
        return this.partnerId;
    }
    
    public void setPartnerId(long partnerId)
    {
        this.partnerId = partnerId;
    }
    
    public String getCompanyName()
    {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName)
    {
        this.companyName = companyName;
    }
    
    public String getTaxCode()
    {
        return taxCode;
    }
    
    public void setTaxCode(String taxCode)
    {
        this.taxCode = taxCode;
    }
    
    public String getBusinessCode()
    {
        return businessCode;
    }
    
    public void setBusinessCode(String businessCode)
    {
        this.businessCode = businessCode;
    }
    
    public String getEmailAddr()
    {
        return this.emailAddr;
    }
    
    public void setEmailAddr(String emailAddr)
    {
        this.emailAddr = emailAddr;
    }
    
    public String getMsidn()
    {
        return this.msidn;
    }
    
    public void setMsidn(String msidn)
    {
        this.msidn = msidn;
    }
    
    public String getBillAddr()
    {
        return this.billAddr;
    }
    
    public void setBillAddr(String billAddr)
    {
        this.billAddr = billAddr;
    }
    
    public Timestamp getValidDate()
    {
        return this.validDate;
    }
    
    public void setValidDate(Timestamp validDate)
    {
        this.validDate = validDate;
    }
    
    public Timestamp getExpiredDate()
    {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Timestamp expiredDate)
    {
        this.expiredDate = expiredDate;
    }
    
    public String getContactName()
    {
        return this.contactName;
    }
    
    public void setContactName(String contactName)
    {
        this.contactName = contactName;
    }
    
    public String getContactMsidn()
    {
        return this.contactMsidn;
    }
    
    public void setContactMsidn(String contactMsidn)
    {
        this.contactMsidn = contactMsidn;
    }
    
    public String getContactEmail()
    {
        return contactEmail;
    }
    
    public void setContactEmail(String contactEmail)
    {
        this.contactEmail = contactEmail;
    }
    
    public Long getPostCode()
    {
        return this.postCode;
    }
    
    public void setPostCode(Long postCode)
    {
        this.postCode = postCode;
    }
    
    public Integer getCountryCode()
    {
        return countryCode;
    }
    
    public void setCountryCode(Integer countryCode)
    {
        this.countryCode = countryCode;
    }
    
    public Integer getCityCode()
    {
        return this.cityCode;
    }
    
    public void setCityCode(Integer cityCode)
    {
        this.cityCode = cityCode;
    }
    
    public Integer getProvinceCode()
    {
        return this.provinceCode;
    }
    
    public void setProvinceCode(Integer provinceCode)
    {
        this.provinceCode = provinceCode;
    }
    
}
