package com.asiainfo.meo.customer.level.app.model.entity;

// Generated 2015-3-17 15:51:24 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCustomerLevelChgHis generated by hbm2java
 */
public class CustomerLevelChgHis implements java.io.Serializable
{
   /**
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么)
    */ 
    private static final long serialVersionUID = -9192569806986498471L;

    public static final Integer STS_VALID   = 0;
    
    public static final Integer STS_INVALID = 1;
    
    private long      id;
    private long      custId;
    private int       orgLevelId;
    private int       curLevelId;
    private Timestamp modifyDate;
    private Timestamp levelValidDate;
    private Timestamp levelExpiredDate;
    private Integer   sts;
    private Timestamp createDate;
    
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public long getCustId()
    {
        return this.custId;
    }
    
    public void setCustId(long custId)
    {
        this.custId = custId;
    }
    
    public int getOrgLevelId()
    {
        return this.orgLevelId;
    }
    
    public void setOrgLevelId(int orgLevelId)
    {
        this.orgLevelId = orgLevelId;
    }
    
    public int getCurLevelId()
    {
        return this.curLevelId;
    }
    
    public void setCurLevelId(int curLevelId)
    {
        this.curLevelId = curLevelId;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getLevelValidDate()
    {
        return this.levelValidDate;
    }
    
    public void setLevelValidDate(Timestamp levelValidDate)
    {
        this.levelValidDate = levelValidDate;
    }
    
    public Timestamp getLevelExpiredDate()
    {
        return this.levelExpiredDate;
    }
    
    public void setLevelExpiredDate(Timestamp levelExpiredDate)
    {
        this.levelExpiredDate = levelExpiredDate;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
}
