package com.asiainfo.meo.customer.level.app.model.entity;
// default package
// Generated 2015-2-28 15:26:34 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;

import com.asiainfo.meo.common.core.validate.group.Insert;
import com.asiainfo.meo.common.core.validate.group.Update;



/**
 * CmLevelRuleMapping generated by hbm2java
 */
public class LevelRuleMapping implements java.io.Serializable
{
    
    /**
     * 
     */
    private static final long serialVersionUID = 4914757384578320978L;
    private int       id;
    @NotNull(groups={Update.class , Insert.class})
    private int       levelRuleId;
    private Integer   levelId;
    private Timestamp validDate;
    private Timestamp expiredDate;
    
    
    public int getId()
    {
        return this.id;
    }
    
    public void setId(int id)
    {
        this.id = id;
    }
    
    public int getLevelRuleId()
    {
        return this.levelRuleId;
    }
    
    public void setLevelRuleId(int levelRuleId)
    {
        this.levelRuleId = levelRuleId;
    }
    
    public Integer getLevelId()
    {
        return this.levelId;
    }
    
    public void setLevelId(Integer levelId)
    {
        this.levelId = levelId;
    }
    
    public Timestamp getValidDate()
    {
        return this.validDate;
    }
    
    public void setValidDate(Timestamp validDate)
    {
        this.validDate = validDate;
    }
    
    public Timestamp getExpiredDate()
    {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Timestamp expiredDate)
    {
        this.expiredDate = expiredDate;
    }
    
}
