package com.asiainfo.meo.system.user.app.model.entity;

// Generated 2015-4-3 16:25:17 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysUserPwd generated by hbm2java
 */
public class SysCustomerPwd implements java.io.Serializable
{
    
    
    private static final long   serialVersionUID    = 7588062765867630550L;
    public static final Integer STS_PWD_INACTIVATE = 0;
    public static final Integer STS_PWD_ACTIVATE   = 1;
    public static final Integer STS_PWD_DEACTIVATE = 2;
    public static final String SYS_CUSTOMER_PWD_SEQ = "SEQ_SYS_CUST_PWD_ID";
    private long                id;
    private long                loginId;
    private String              pwd;
    private Integer             pwdType;
    private Integer             question1;
    private String              answer1;
    private Integer             question2;
    private String              answer2;
    private Integer             question3;
    private String              answer3;
    private Timestamp           createDate;
    private Timestamp           modifyDate;
    private Timestamp           lastModifyPwdTime;
    private Integer             sts;
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public long getLoginId()
    {
        return this.loginId;
    }
    
    public void setLoginId(long loginId)
    {
        this.loginId = loginId;
    }
    
    public String getPwd()
    {
        return this.pwd;
    }
    
    public void setPwd(String pwd)
    {
        this.pwd = pwd;
    }
    
    public Integer getPwdType()
    {
        return this.pwdType;
    }
    
    public void setPwdType(Integer pwdType)
    {
        this.pwdType = pwdType;
    }
    
    public Integer getQuestion1()
    {
        return this.question1;
    }
    
    public void setQuestion1(Integer question1)
    {
        this.question1 = question1;
    }
    
    public String getAnswer1()
    {
        return this.answer1;
    }
    
    public void setAnswer1(String answer1)
    {
        this.answer1 = answer1;
    }
    
    public Integer getQuestion2()
    {
        return this.question2;
    }
    
    public void setQuestion2(Integer question2)
    {
        this.question2 = question2;
    }
    
    public String getAnswer2()
    {
        return this.answer2;
    }
    
    public void setAnswer2(String answer2)
    {
        this.answer2 = answer2;
    }
    
    public Integer getQuestion3()
    {
        return this.question3;
    }
    
    public void setQuestion3(Integer question3)
    {
        this.question3 = question3;
    }
    
    public String getAnswer3()
    {
        return this.answer3;
    }
    
    public void setAnswer3(String answer3)
    {
        this.answer3 = answer3;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getLastModifyPwdTime()
    {
        return this.lastModifyPwdTime;
    }
    
    public void setLastModifyPwdTime(Timestamp lastModifyPwdTime)
    {
        this.lastModifyPwdTime = lastModifyPwdTime;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
}
