package com.asiainfo.meo.activity.business.model.entity;

// Generated 2015-5-15 10:28:04 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmRewardActivity generated by hbm2java
 */
public class CmRewardActivity implements java.io.Serializable {

	public static final Integer REWARD_TYPE_COIN = 1;
    public static final String REWARD_ACTIVITY_SEQ = "SEQ_REWARD_ACTIVITY_ID";
    private long rewardId;
	private Long activityId;
	private String campaignNo;
	private Long custId;
	private Timestamp doneTime;
	private Integer rewardType;
	private Long rewardValue;
	private Integer rewardUnit;
	private Long actionId;
	private Long taskId;

	public CmRewardActivity() {
	}

	public CmRewardActivity(long rewardId) {
		this.rewardId = rewardId;
	}

	public CmRewardActivity(long rewardId, Long activityId, String campaignNo,
			Long custId, Timestamp doneTime, Integer rewardType,
			Long rewardValue, Integer rewardUnit, Long actionId, Long taskId) {
		this.rewardId = rewardId;
		this.activityId = activityId;
		this.campaignNo = campaignNo;
		this.custId = custId;
		this.doneTime = doneTime;
		this.rewardType = rewardType;
		this.rewardValue = rewardValue;
		this.rewardUnit = rewardUnit;
		this.actionId = actionId;
		this.taskId = taskId;
	}

	public long getRewardId() {
		return this.rewardId;
	}

	public void setRewardId(long rewardId) {
		this.rewardId = rewardId;
	}

	public Long getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

	public String getCampaignNo() {
		return this.campaignNo;
	}

	public void setCampaignNo(String campaignNo) {
		this.campaignNo = campaignNo;
	}

	public Long getCustId() {
		return this.custId;
	}

	public void setCustId(Long custId) {
		this.custId = custId;
	}

	public Timestamp getDoneTime() {
		return this.doneTime;
	}

	public void setDoneTime(Timestamp doneTime) {
		this.doneTime = doneTime;
	}

	public Integer getRewardType() {
		return this.rewardType;
	}

	public void setRewardType(Integer rewardType) {
		this.rewardType = rewardType;
	}

	public Long getRewardValue() {
		return this.rewardValue;
	}

	public void setRewardValue(Long rewardValue) {
		this.rewardValue = rewardValue;
	}

	public Integer getRewardUnit() {
		return this.rewardUnit;
	}

	public void setRewardUnit(Integer rewardUnit) {
		this.rewardUnit = rewardUnit;
	}

	public Long getActionId() {
		return this.actionId;
	}

	public void setActionId(Long actionId) {
		this.actionId = actionId;
	}

	public Long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

}
