package com.asiainfo.meo.campaign.task.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaignTaskRuleRel generated by hbm2java
 */
public class CampaignTaskRuleRel implements java.io.Serializable
{
    private static final long serialVersionUID = -4774898146358071858L;
    
    private long              id;
    
    private long              taskId;
    
    private Long              ruleId;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private String            description;
    
    private Integer           sts;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public long getTaskId()
    {
        return this.taskId;
    }
    
    public void setTaskId(long taskId)
    {
        this.taskId = taskId;
    }
    
    public Long getRuleId()
    {
        return this.ruleId;
    }
    
    public void setRuleId(Long ruleId)
    {
        this.ruleId = ruleId;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public String getDescription()
    {
        return this.description;
    }
    
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
}
