package com.asiainfo.meo.campaign.task.app.model.entity;

import java.sql.Timestamp;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

/**
 * CmCampaignTaskRule generated by hbm2java
 */
public class CampaignTaskRule implements java.io.Serializable
{
    private static final long serialVersionUID = 8729466075687004936L;
    
    private long              ruleId;
    
    private long              actionId;
    
    private String            ruleContent;
    
    private Integer           ruleType;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Timestamp         operatorId;
    
    private Integer           sts;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getRuleId()
    {
        return ruleId;
    }
    
    public void setRuleId(long ruleId)
    {
        this.ruleId = ruleId;
    }
    
    public long getActionId()
    {
        return actionId;
    }
    
    public void setActionId(long actionId)
    {
        this.actionId = actionId;
    }
    
    public String getRuleContent()
    {
        return ruleContent;
    }
    
    public void setRuleContent(String ruleContent)
    {
        this.ruleContent = ruleContent;
    }
    
    public Integer getRuleType()
    {
        return ruleType;
    }
    
    public void setRuleType(Integer ruleType)
    {
        this.ruleType = ruleType;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getOperatorId()
    {
        return operatorId;
    }
    
    public void setOperatorId(Timestamp operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
}
