package com.asiainfo.meo.campaign.task.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaignTask generated by hbm2java
 */
public class CampaignTask implements java.io.Serializable
{
    private static final long serialVersionUID = -7611594467528773035L;
    
    private long              taskId;
    
    private long              actionId;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private String            description;
    
    private Long              campaignId;
    
    private Integer               sts;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getTaskId()
    {
        return taskId;
    }
    
    public void setTaskId(long taskId)
    {
        this.taskId = taskId;
    }
    
    public long getActionId()
    {
        return actionId;
    }
    
    public void setActionId(long actionId)
    {
        this.actionId = actionId;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public String getDescription()
    {
        return description;
    }
    
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    public Long getCampaignId()
    {
        return campaignId;
    }
    
    public void setCampaignId(Long campaignId)
    {
        this.campaignId = campaignId;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
}
