package com.asiainfo.meo.campaign.task.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaignTaskRel generated by hbm2java
 */
public class CampaignTaskRel implements java.io.Serializable
{
    private static final long serialVersionUID = -5197858088905416930L;
    
    public static final int   REL_TYPE_TRIGGER = 1;
    
    public static final int   REL_TYPE_PARENT  = 2;
    
    private long              relId;
    
    private long              srcTaskId;
    
    private long              destTaskId;
    
    private int               relTypeId;
    
    private Timestamp         modifyDate;
    
    private Timestamp         createDate;
    
    private Long              campaignId;
    
    private Integer           sts;
    
    /** price status constant */
    public static final int   STS_VALID        = 1;
    
    /** price status constant */
    public static final int   STS_INVALID      = 2;
    
    public long getRelId()
    {
        return relId;
    }
    
    public void setRelId(long relId)
    {
        this.relId = relId;
    }
    
    public long getSrcTaskId()
    {
        return srcTaskId;
    }
    
    public void setSrcTaskId(long srcTaskId)
    {
        this.srcTaskId = srcTaskId;
    }
    
    public long getDestTaskId()
    {
        return destTaskId;
    }
    
    public void setDestTaskId(long destTaskId)
    {
        this.destTaskId = destTaskId;
    }
    
    public int getRelTypeId()
    {
        return relTypeId;
    }
    
    public void setRelTypeId(int relTypeId)
    {
        this.relTypeId = relTypeId;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Long getCampaignId()
    {
        return campaignId;
    }
    
    public void setCampaignId(Long campaignId)
    {
        this.campaignId = campaignId;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
}
