package com.asiainfo.meo.campaign.task.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmTaskParamInstance generated by hbm2java
 */
public class TaskParamInstance implements java.io.Serializable
{
    private static final long serialVersionUID = -4568440889802445925L;
    
    private long              paramInstanceId;
    
    private long              taskId;
    
    private long              paramId;
    
    private long              paramValue;
    
    private Integer           paramValueUnit;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Integer           sts;
    
    /** price status constant */
    public static final int   STS_VALID        = 1;
    
    /** price status constant */
    public static final int   STS_INVALID      = 2;
    
    public long getParamInstanceId()
    {
        return paramInstanceId;
    }
    
    public void setParamInstanceId(long paramInstanceId)
    {
        this.paramInstanceId = paramInstanceId;
    }
    
    public long getTaskId()
    {
        return taskId;
    }
    
    public void setTaskId(long taskId)
    {
        this.taskId = taskId;
    }
    
    public long getParamId()
    {
        return paramId;
    }
    
    public void setParamId(long paramId)
    {
        this.paramId = paramId;
    }
    
    public long getParamValue()
    {
        return paramValue;
    }
    
    public void setParamValue(long paramValue)
    {
        this.paramValue = paramValue;
    }
    
    public Integer getParamValueUnit()
    {
        return paramValueUnit;
    }
    
    public void setParamValueUnit(Integer paramValueUnit)
    {
        this.paramValueUnit = paramValueUnit;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
}
