package com.asiainfo.meo.campaign.task.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmTaskRelTypeDef generated by hbm2java
 */
public class TaskRelTypeDef implements java.io.Serializable
{
    private static final long serialVersionUID = 552623718973277060L;
    
    private int               relTypeId;
    
    private String            relTypeName;
    
    private String            description;
    
    private Integer           sts;
    
    private Timestamp         modifyDate;
    
    private Timestamp         createDate;
    
    public int getRelTypeId()
    {
        return this.relTypeId;
    }
    
    public void setRelTypeId(int relTypeId)
    {
        this.relTypeId = relTypeId;
    }
    
    public String getRelTypeName()
    {
        return this.relTypeName;
    }
    
    public void setRelTypeName(String relTypeName)
    {
        this.relTypeName = relTypeName;
    }
    
    public String getDescription()
    {
        return this.description;
    }
    
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
}
