package com.asiainfo.meo.system.authority.app.model.entity;

// Generated 2015-4-3 16:25:17 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysMenu generated by hbm2java
 */
public class SysMenu implements java.io.Serializable
{
    
    private long      menuId;
    
    private String    name;
    
    private Long      parentId;
    
    private String    url;
    
    private Long      systemId;
    
    private Long      moduleId;
    
    private Integer   menuLevel;
    
    private Integer   languageCode;
    
    private Integer   sts;
    
    private Timestamp createDate;
    
    private Timestamp modifyDate;
    
    private Integer menuType;
    
    private String iconUrl;
    
    public static final Integer STS_VALID = 1;
    
    public  static final Integer STS_INVALID = 2;
    
    public Integer getMenuType()
    {
        return menuType;
    }

    public void setMenuType(Integer menuType)
    {
        this.menuType = menuType;
    }

    public String getIconUrl()
    {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl)
    {
        this.iconUrl = iconUrl;
    }

    public long getMenuId()
    {
        return this.menuId;
    }
    
    public void setMenuId(long menuId)
    {
        this.menuId = menuId;
    }
    
    public String getName()
    {
        return this.name;
    }
    
    public void setName(String name)
    {
        this.name = name;
    }
    
    public Long getParentId()
    {
        return this.parentId;
    }
    
    public void setParentId(Long parentId)
    {
        this.parentId = parentId;
    }
    
    public String getUrl()
    {
        return this.url;
    }
    
    public void setUrl(String url)
    {
        this.url = url;
    }
    
    public Long getSystemId()
    {
        return this.systemId;
    }
    
    public void setSystemId(Long systemId)
    {
        this.systemId = systemId;
    }
    
    public Long getModuleId()
    {
        return this.moduleId;
    }
    
    public void setModuleId(Long moduleId)
    {
        this.moduleId = moduleId;
    }
    
    public Integer getMenuLevel()
    {
        return this.menuLevel;
    }
    
    public void setMenuLevel(Integer menuLevel)
    {
        this.menuLevel = menuLevel;
    }
    
    public Integer getLanguageCode()
    {
        return this.languageCode;
    }
    
    public void setLanguageCode(Integer languageCode)
    {
        this.languageCode = languageCode;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
}
