package com.asiainfo.meo.system.authority.app.model.entity;

// Generated 2015-4-3 16:25:17 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysPrivilege generated by hbm2java
 */
public class SysPrivilege implements java.io.Serializable
{
    
    private long      privId;
    
    private String    privCode;
    
    private String    privName;
    
    private Integer   privType;
    
    private Long      parentId;
    
    private Long      systemId;
    
    private Long      moduleId;
    
    private Integer   sts;
    
    private Timestamp createDate;
    
    private Timestamp modifyDate;
    
    public static final Integer STS_VALID = 1;
    
    public  static final Integer STS_INVALID = 2;
    
    public long getPrivId()
    {
        return this.privId;
    }
    
    public void setPrivId(long privId)
    {
        this.privId = privId;
    }
    
    public String getPrivCode()
    {
        return this.privCode;
    }
    
    public void setPrivCode(String privCode)
    {
        this.privCode = privCode;
    }
    
    public String getPrivName()
    {
        return this.privName;
    }
    
    public void setPrivName(String privName)
    {
        this.privName = privName;
    }
    
    public Integer getPrivType()
    {
        return this.privType;
    }
    
    public void setPrivType(Integer privType)
    {
        this.privType = privType;
    }
    
    public Long getParentId()
    {
        return this.parentId;
    }
    
    public void setParentId(Long parentId)
    {
        this.parentId = parentId;
    }
    
    public Long getSystemId()
    {
        return this.systemId;
    }
    
    public void setSystemId(Long systemId)
    {
        this.systemId = systemId;
    }
    
    public Long getModuleId()
    {
        return this.moduleId;
    }
    
    public void setModuleId(Long moduleId)
    {
        this.moduleId = moduleId;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
}
