package com.asiainfo.meo.product.profile.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmPrice generated by hbm2java
 */
public class DiscountRule implements java.io.Serializable
{
    
    public static final String  SEQ_PD_DISCOUNT_RULE_DEF = "SEQ_PD_DISCOUNT_RULE_ID";
    
    private static final long serialVersionUID = 1L;
    
    private long              discountId;
    
    private String            discountName;
    
    private Long              minCount;
    
    private Long              maxCount;
    
    private Long              discountPrice;
    
    private Integer           unit;
    
    private Integer           discountType;
    
    private Integer           sts;
    
    private Timestamp         disValidDate;
    
    private Timestamp         disExpireddate;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    public static final Integer   STS_VALID        = 1;
    
    public static final Integer   STS_INVALID      = 2;

    public long getDiscountId()
    {
        return discountId;
    }

    public void setDiscountId(long discountId)
    {
        this.discountId = discountId;
    }

    public String getDiscountName()
    {
        return discountName;
    }

    public void setDiscountName(String discountName)
    {
        this.discountName = discountName;
    }

    public Long getMinCount()
    {
        return minCount;
    }

    public void setMinCount(Long minCount)
    {
        this.minCount = minCount;
    }

    public Long getMaxCount()
    {
        return maxCount;
    }

    public void setMaxCount(Long maxCount)
    {
        this.maxCount = maxCount;
    }

    public Long getDiscountPrice()
    {
        return discountPrice;
    }

    public void setDiscountPrice(Long discountPrice)
    {
        this.discountPrice = discountPrice;
    }

    public Integer getUnit()
    {
        return unit;
    }

    public void setUnit(Integer unit)
    {
        this.unit = unit;
    }

    public Integer getDiscountType()
    {
        return discountType;
    }

    public void setDiscountType(Integer discountType)
    {
        this.discountType = discountType;
    }

    public Integer getSts()
    {
        return sts;
    }

    public void setSts(Integer sts)
    {
        this.sts = sts;
    }

    public Timestamp getDisValidDate()
    {
        return disValidDate;
    }

    public void setDisValidDate(Timestamp disValidDate)
    {
        this.disValidDate = disValidDate;
    }

    public Timestamp getDisExpireddate()
    {
        return disExpireddate;
    }

    public void setDisExpireddate(Timestamp disExpireddate)
    {
        this.disExpireddate = disExpireddate;
    }

    public Timestamp getCreateDate()
    {
        return createDate;
    }

    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }

    public Timestamp getModifyDate()
    {
        return modifyDate;
    }

    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
}
