package com.asiainfo.meo.product.profile.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmPrice generated by hbm2java
 */
public class PdPrice implements java.io.Serializable
{
    
    public static final String  SEQ_PD_PRICE_DEF = "SEQ_PD_PRICE_ID";
    
    private static final long serialVersionUID = 1L;
    
    private long              priceId;
    
    private String            priceName;
    
    private Long              price;
    
    private Integer           priceUnit;
    
    private Integer           priceType;
    
    private Integer           sts;
    
    private Timestamp         validDate;
    
    private Timestamp         expiredDate;
    
    private Timestamp         modifyDate;
    
    private Timestamp         createDate;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public Long getPrice()
    {
        return price;
    }
    
    public void setPrice(Long price)
    {
        this.price = price;
    }
    
    public long getPriceId()
    {
        return priceId;
    }
    
    public void setPriceId(long priceId)
    {
        this.priceId = priceId;
    }
    
    public String getPriceName()
    {
        return priceName;
    }
    
    public void setPriceName(String priceName)
    {
        this.priceName = priceName;
    }
    
    public Integer getPriceUnit()
    {
        return priceUnit;
    }
    
    public void setPriceUnit(Integer priceUnit)
    {
        this.priceUnit = priceUnit;
    }
    
    public Integer getPriceType()
    {
        return priceType;
    }
    
    public void setPriceType(Integer priceType)
    {
        this.priceType = priceType;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getValidDate()
    {
        return validDate;
    }
    
    public void setValidDate(Timestamp validDate)
    {
        this.validDate = validDate;
    }
    
    public Timestamp getExpiredDate()
    {
        return expiredDate;
    }
    
    public void setExpiredDate(Timestamp expiredDate)
    {
        this.expiredDate = expiredDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
}
