package com.asiainfo.meo.product.profile.app.model.entity;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * PdProduct generated by hbm2java
 */
public class Product implements java.io.Serializable
{
    
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 1L;
    
    public static final int   STS_INACTIVE     = 1;
    
    public static final int   STS_ACTIVE       = 2;
    
    public static final int   STS_DEACTIVATED  = 3;
    
    public static final String PRODUCT_CYCLE_TYPE = "22";
    
    public static final String PRODUCT_STATUS_TYPE = "21";
    
    public static final String PRODUCT_TYPE = "20";
    
    private long              productId;
    
    private String            productName;
    
    private String            description;
    
    private Integer           prodSts;
    
    private Timestamp         prodStsDate;
    
    private String            imgUrl;
    
    private Integer           denomination;
    
    private Integer           denominationUnit;
    
    private Integer           categoryId;
    
    private Timestamp         validDate;
    
    private Timestamp         expiredDate;
    
    private Timestamp createDate;
    
    private Timestamp modifyDate;
    
    private Integer           sts;
    
    private Long              operatorId;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;

    public long getProductId()
    {
        return productId;
    }

    public void setProductId(long productId)
    {
        this.productId = productId;
    }

    public String getProductName()
    {
        return productName;
    }

    public void setProductName(String productName)
    {
        this.productName = productName;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public Integer getProdSts()
    {
        return prodSts;
    }

    public void setProdSts(Integer prodSts)
    {
        this.prodSts = prodSts;
    }

    public Timestamp getProdStsDate()
    {
        return prodStsDate;
    }

    public void setProdStsDate(Timestamp prodStsDate)
    {
        this.prodStsDate = prodStsDate;
    }

    public String getImgUrl()
    {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl)
    {
        this.imgUrl = imgUrl;
    }

    public Integer getDenomination()
    {
        return denomination;
    }

    public void setDenomination(Integer denomination)
    {
        this.denomination = denomination;
    }

    public Integer getDenominationUnit()
    {
        return denominationUnit;
    }

    public void setDenominationUnit(Integer denominationUnit)
    {
        this.denominationUnit = denominationUnit;
    }

    public Integer getCategoryId()
    {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId)
    {
        this.categoryId = categoryId;
    }

    public Timestamp getValidDate()
    {
        return validDate;
    }

    public void setValidDate(Timestamp validDate)
    {
        this.validDate = validDate;
    }

    public Timestamp getExpiredDate()
    {
        return expiredDate;
    }

    public void setExpiredDate(Timestamp expiredDate)
    {
        this.expiredDate = expiredDate;
    }

    public Timestamp getCreateDate()
    {
        return createDate;
    }

    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }

    public Timestamp getModifyDate()
    {
        return modifyDate;
    }

    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }

    public Integer getSts()
    {
        return sts;
    }

    public void setSts(Integer sts)
    {
        this.sts = sts;
    }

    public Long getOperatorId()
    {
        return operatorId;
    }

    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }

    public static long getSerialversionuid()
    {
        return serialVersionUID;
    }

    public static int getStsInactive()
    {
        return STS_INACTIVE;
    }

    public static int getStsActive()
    {
        return STS_ACTIVE;
    }

    public static int getStsDeactivated()
    {
        return STS_DEACTIVATED;
    }
    

}
