package com.asiainfo.meo.product.profile.app.model.entity;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * PdProductSpec generated by hbm2java
 */
public class ProductSpec implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    
    public static final String COUNTRY_TYPE = "12323323";
    
    public static final String CITY_TYPE = "123233";
    
    public static final String PROVINCE_TYPE = "123233";
    
    private static final long serialVersionUID = 1L;
    
    private long              proSpecId;
    
    private Integer           levelId;
    
    private Integer           validationPeriod;
    
    private Integer           validationPeriodUnit;
    
    private Integer           activationPeriod;
    
    private Integer           activationPeriodUnit;
    
    private Integer           sts;
    
    private Timestamp         modifyDate;
    
    private Timestamp         createTime;
    
    private Integer           countryCode;
    
    private Integer           provCode;
    
    private Integer           cityCode;
    
    private Integer           prodCycleType;
    
    private Long              productId;
    
    private String            ip;
    
    private String            port;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getProSpecId()
    {
        return proSpecId;
    }
    
    public void setProSpecId(long proSpecId)
    {
        this.proSpecId = proSpecId;
    }
    
    public Integer getLevelId()
    {
        return levelId;
    }
    
    public void setLevelId(Integer levelId)
    {
        this.levelId = levelId;
    }
    
    public Integer getValidationPeriod()
    {
        return validationPeriod;
    }
    
    public void setValidationPeriod(Integer validationPeriod)
    {
        this.validationPeriod = validationPeriod;
    }
    
    public Integer getValidationPeriodUnit()
    {
        return validationPeriodUnit;
    }
    
    public void setValidationPeriodUnit(Integer validationPeriodUnit)
    {
        this.validationPeriodUnit = validationPeriodUnit;
    }
    
    public Integer getActivationPeriod()
    {
        return activationPeriod;
    }
    
    public void setActivationPeriod(Integer activationPeriod)
    {
        this.activationPeriod = activationPeriod;
    }
    
    public Integer getActivationPeriodUnit()
    {
        return activationPeriodUnit;
    }
    
    public void setActivationPeriodUnit(Integer activationPeriodUnit)
    {
        this.activationPeriodUnit = activationPeriodUnit;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getCreateTime()
    {
        return createTime;
    }
    
    public void setCreateTime(Timestamp createTime)
    {
        this.createTime = createTime;
    }
    
    public Integer getCountryCode()
    {
        return countryCode;
    }
    
    public void setCountryCode(Integer countryCode)
    {
        this.countryCode = countryCode;
    }
    
    public Integer getProvCode()
    {
        return provCode;
    }
    
    public void setProvCode(Integer provCode)
    {
        this.provCode = provCode;
    }
    
    public Integer getCityCode()
    {
        return cityCode;
    }
    
    public void setCityCode(Integer cityCode)
    {
        this.cityCode = cityCode;
    }
    
    public Integer getProdCycleType()
    {
        return prodCycleType;
    }
    
    public void setProdCycleType(Integer prodCycleType)
    {
        this.prodCycleType = prodCycleType;
    }
    
    public Long getProductId()
    {
        return productId;
    }
    
    public void setProductId(Long productId)
    {
        this.productId = productId;
    }
    
    public String getIp()
    {
        return ip;
    }
    
    public void setIp(String ip)
    {
        this.ip = ip;
    }
    
    public String getPort()
    {
        return port;
    }
    
    public void setPort(String port)
    {
        this.port = port;
    }
    
}
