package com.asiainfo.meo.campaign.profile.app.model.vo;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

/**
 * CmCampaign generated by hbm2java
 */
public class CampaignVO implements java.io.Serializable
{
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 1L;
    
    private Long              campaignId;
    
    private String            campaignName;
    
    private String            iconUrl;
    
    private Integer           categoryId;
    
    private String            categoryName;
    
    private Integer           campaignType;
    
    private Integer           totalCoins;
    
    // added by zhengzy 2015-9-10 17:33:56
    private Integer           participant;
    
    private Integer           remainParticipant;
    
    public Long getCampaignId()
    {
        return campaignId;
    }
    
    public void setCampaignId(Long campaignId)
    {
        this.campaignId = campaignId;
    }
    
    public String getCampaignName()
    {
        return campaignName;
    }
    
    public void setCampaignName(String campaignName)
    {
        this.campaignName = campaignName;
    }
    
    public String getIconUrl()
    {
        return iconUrl;
    }
    
    public void setIconUrl(String iconUrl)
    {
        this.iconUrl = iconUrl;
    }
    
    public Integer getCategoryId()
    {
        return categoryId;
    }
    
    public void setCategoryId(Integer categoryId)
    {
        this.categoryId = categoryId;
    }
    
    public String getCategoryName()
    {
        return categoryName;
    }
    
    public void setCategoryName(String categoryName)
    {
        this.categoryName = categoryName;
    }
    
    public Integer getCampaignType()
    {
        return campaignType;
    }
    
    public void setCampaignType(Integer campaignType)
    {
        this.campaignType = campaignType;
    }
    
    public Integer getTotalCoins()
    {
        return totalCoins;
    }
    
    public void setTotalCoins(Integer totalCoins)
    {
        this.totalCoins = totalCoins;
    }
    
    public Integer getParticipant()
    {
        return participant;
    }
    
    public void setParticipant(Integer participant)
    {
        this.participant = participant;
    }

    public Integer getRemainParticipant()
    {
        return remainParticipant;
    }

    public void setRemainParticipant(Integer remainParticipant)
    {
        this.remainParticipant = remainParticipant;
    }
    
}
