package com.asiainfo.meo.meo.notification.configuration.model.vo;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

/**
 * SysNotificationDef generated by hbm2java
 */
public class NotificationDefVO implements java.io.Serializable
{
    
    private Long    notifId;
    
    private Long    templateId;
    
    private String  templateName;
    
    private String  notifName;
    
    private String  notifDesc;
    
    private Long    operatorId;
    
    private Integer notifTypeId;
    
    private String  notifType;

    public String getTemplateName()
    {
        return templateName;
    }

    public void setTemplateName(String templateName)
    {
        this.templateName = templateName;
    }

    public Long getNotifId()
    {
        return notifId;
    }
    
    public void setNotifId(Long notifId)
    {
        this.notifId = notifId;
    }
    
    public Long getTemplateId()
    {
        return templateId;
    }
    
    public void setTemplateId(Long templateId)
    {
        this.templateId = templateId;
    }
    
    public String getNotifName()
    {
        return notifName;
    }
    
    public void setNotifName(String notifName)
    {
        this.notifName = notifName;
    }
    
    public String getNotifDesc()
    {
        return notifDesc;
    }
    
    public void setNotifDesc(String notifDesc)
    {
        this.notifDesc = notifDesc;
    }
    
    public Long getOperatorId()
    {
        return operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public Integer getNotifTypeId()
    {
        return notifTypeId;
    }
    
    public void setNotifTypeId(Integer notifTypeId)
    {
        this.notifTypeId = notifTypeId;
    }
    
    public String getNotifType()
    {
        return notifType;
    }
    
    public void setNotifType(String notifType)
    {
        this.notifType = notifType;
    }
    
}
