package com.asiainfo.meo.customer.resource.app.model.entity;

// Generated 2015-3-2 14:55:03 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;

import com.asiainfo.meo.common.core.validate.group.Insert;
import com.asiainfo.meo.common.core.validate.group.Update;

/**
 * CmResource generated by hbm2java
 */
public class CmResource implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么)
     */
    private static final long   serialVersionUID      = -3356656529746368982L;
    
    private long                resourceId;
    
    private Long                custId;
    
    private Long                productId;
    
    @NotNull(groups = {Update.class, Insert.class })
    private int                 resType;
    
    public static final Integer RES_TYPE_DATA_PACKAGE = 0;
    
    private Timestamp           cycleBeginDate;
    
    private Timestamp           cycleEndDate;
    
    @NotNull(groups = {Update.class, Insert.class })
    private int                 resSts;
    
    private Timestamp           modifyDate;
    
    private Timestamp           createDate;
    
    public static final Integer RES_STATUS_REDEEM     = 1;
    
    public static final Integer RES_STATUS_ACTIVE     = 2;
    
    public static final Integer RES_STATUS_EXPIRED    = 3;
    
    public long getResourceId()
    {
        return this.resourceId;
    }
    
    public void setResourceId(long resourceId)
    {
        this.resourceId = resourceId;
    }
    
    public Long getCustId()
    {
        return this.custId;
    }
    
    public void setCustId(Long custId)
    {
        this.custId = custId;
    }
    
    public Long getProductId()
    {
        return this.productId;
    }
    
    public void setProductId(Long productId)
    {
        this.productId = productId;
    }
    
    public int getResType()
    {
        return this.resType;
    }
    
    public void setResType(int resType)
    {
        this.resType = resType;
    }
    
    public Timestamp getCycleBeginDate()
    {
        return this.cycleBeginDate;
    }
    
    public void setCycleBeginDate(Timestamp cycleBeginDate)
    {
        this.cycleBeginDate = cycleBeginDate;
    }
    
    public Timestamp getCycleEndDate()
    {
        return this.cycleEndDate;
    }
    
    public void setCycleEndDate(Timestamp cycleEndDate)
    {
        this.cycleEndDate = cycleEndDate;
    }
    
    public int getResSts()
    {
        return this.resSts;
    }
    
    public void setResSts(int resSts)
    {
        this.resSts = resSts;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
}
