package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-3-25 16:30:00 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysEnumDef generated by hbm2java
 */

public class SysActionDef implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID   = 1L;
    
    private long              actionId;
    
    private String            actionName;
    
    private Integer           actionType;
    
    private String            actionDesc;
    
    private Integer           sts;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Long              operatorId;
    
    public static final int   PREDECESSOR_ACTION = 1;
    
    public static final int   SUCESSOR_ACTION    = 2;
    
    public long getActionId()
    {
        return actionId;
    }
    
    public void setActionId(long actionId)
    {
        this.actionId = actionId;
    }
    
    public String getActionName()
    {
        return actionName;
    }
    
    public void setActionName(String actionName)
    {
        this.actionName = actionName;
    }
    
    public Integer getActionType()
    {
        return actionType;
    }
    
    public void setActionType(Integer actionType)
    {
        this.actionType = actionType;
    }
    
    public String getActionDesc()
    {
        return actionDesc;
    }
    
    public void setActionDesc(String actionDesc)
    {
        this.actionDesc = actionDesc;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
}
