package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmAgreement generated by hbm2java
 */
public class SysActionRel implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long   serialVersionUID = 1L;
    
    private long                relId;
    
    private Integer             sts;
    
    private Timestamp           createDate;
    
    private Timestamp           modifyDate;
    
    private Integer             relType;
    
    private Long                srcActionId;
    
    private Long                destActionId;
    
    private Long                operatorId;
    
    public static final Integer TRIGGER_TYPE     = 1;
    
    public static final Integer STS_VALID        = 1;
    
    public static final Integer STS_INVALID      = 2;
    
    public long getRelId()
    {
        return relId;
    }
    
    public void setRelId(long relId)
    {
        this.relId = relId;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Integer getRelType()
    {
        return relType;
    }
    
    public void setRelType(Integer relType)
    {
        this.relType = relType;
    }
    
    public Long getSrcActionId()
    {
        return srcActionId;
    }
    
    public void setSrcActionId(Long srcActionId)
    {
        this.srcActionId = srcActionId;
    }
    
    public Long getDestActionId()
    {
        return destActionId;
    }
    
    public void setDestActionId(Long destActionId)
    {
        this.destActionId = destActionId;
    }
    
    public Long getOperatorId()
    {
        return operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
}
