package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysActionParamDef generated by hbm2java
 */
public class SysActionParamDef implements java.io.Serializable
{
    private static final long serialVersionUID = -7102412126237845445L;
    
    private long              paramId;
    
    private String            actionId;
    
    private String            paramName;
    
    private int               sts;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Long              operatorId;
    
    private int               paramDataType;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getParamId()
    {
        return this.paramId;
    }
    
    public void setParamId(long paramId)
    {
        this.paramId = paramId;
    }
    
    public String getActionId()
    {
        return this.actionId;
    }
    
    public void setActionId(String actionId)
    {
        this.actionId = actionId;
    }
    
    public String getParamName()
    {
        return this.paramName;
    }
    
    public void setParamName(String paramName)
    {
        this.paramName = paramName;
    }
    
    public int getSts()
    {
        return this.sts;
    }
    
    public void setSts(int sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public int getParamDataType()
    {
        return this.paramDataType;
    }
    
    public void setParamDataType(int paramDataType)
    {
        this.paramDataType = paramDataType;
    }
    
}
