package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysCountryDef generated by hbm2java
 */
public class SysCountryDef implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 1L;
    
    private long              countryCode;
    
    private String            name;
    
    private String            nameAbbreviation;
    
    private Integer           sts;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Integer           type;
    
    private Long              operatorId;
    
    private Integer           languageCode;
    
    public long getCountryCode()
    {
        return this.countryCode;
    }
    
    public void setCountryCode(long countryCode)
    {
        this.countryCode = countryCode;
    }
    
    public String getName()
    {
        return this.name;
    }
    
    public void setName(String name)
    {
        this.name = name;
    }
    
    public String getNameAbbreviation()
    {
        return this.nameAbbreviation;
    }
    
    public void setNameAbbreviation(String nameAbbreviation)
    {
        this.nameAbbreviation = nameAbbreviation;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Integer getType()
    {
        return this.type;
    }
    
    public void setType(Integer type)
    {
        this.type = type;
    }
    
    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public Integer getLanguageCode()
    {
        return this.languageCode;
    }
    
    public void setLanguageCode(Integer languageCode)
    {
        this.languageCode = languageCode;
    }
    
}
