package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmAgreement generated by hbm2java
 */
public class SysCampaignActionDef implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long   serialVersionUID = 1L;
    
    private long                defId;
    
    private Long                actionId;
    
    private Integer             campaignType;
    
    private Integer             sts;
    
    private Timestamp           createDate;
    
    private Timestamp           modifyDate;
    
    private Long                operatorId;
    
    public static final Integer STS_VALID        = 1;
    
    public static final Integer STS_INVALID      = 2;
    
    public long getDefId()
    {
        return defId;
    }
    
    public void setDefId(long defId)
    {
        this.defId = defId;
    }
    
    public Long getActionId()
    {
        return actionId;
    }
    
    public void setActionId(Long actionId)
    {
        this.actionId = actionId;
    }
    
    public Integer getCampaignType()
    {
        return campaignType;
    }
    
    public void setCampaignType(Integer campaignType)
    {
        this.campaignType = campaignType;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
}
