package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-4-24 16:02:31 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysConfigurationDef generated by hbm2java
 */
public class SysConfigurationDef implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 1L;
    
    private long              configId;
    
    private String            configCode;
    
    private String            configName;
    
    private String            configDesc;
    
    private String            configValueCode;
    
    private String            configValueDesc;
    
    private String            configValueType;
    
    private int               configValue;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Long              operatorId;
    
    private int               sts;
    
    public long getConfigId()
    {
        return this.configId;
    }
    
    public void setConfigId(long configId)
    {
        this.configId = configId;
    }
    
    public String getConfigCode()
    {
        return this.configCode;
    }
    
    public void setConfigCode(String configCode)
    {
        this.configCode = configCode;
    }
    
    public String getConfigName()
    {
        return this.configName;
    }
    
    public void setConfigName(String configName)
    {
        this.configName = configName;
    }
    
    public String getConfigDesc()
    {
        return this.configDesc;
    }
    
    public void setConfigDesc(String configDesc)
    {
        this.configDesc = configDesc;
    }
    
    public String getConfigValueCode()
    {
        return this.configValueCode;
    }
    
    public void setConfigValueCode(String configValueCode)
    {
        this.configValueCode = configValueCode;
    }
    
    public String getConfigValueDesc()
    {
        return this.configValueDesc;
    }
    
    public void setConfigValueDesc(String configValueDesc)
    {
        this.configValueDesc = configValueDesc;
    }
    
    public String getConfigValueType()
    {
        return this.configValueType;
    }
    
    public void setConfigValueType(String configValueType)
    {
        this.configValueType = configValueType;
    }
    
    public int getConfigValue()
    {
        return this.configValue;
    }
    
    public void setConfigValue(int configValue)
    {
        this.configValue = configValue;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public int getSts()
    {
        return this.sts;
    }
    
    public void setSts(int sts)
    {
        this.sts = sts;
    }
    
}
