package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-4-9 13:11:57 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysMeasureUnitExchangeRule generated by hbm2java
 */
public class SysMeasureUnitExchangeRule implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 1L;
    
    private long              ruleId;
    
    private Long              measureId;
    
    private Long              destMeasureId;
    
    private Long              measureExchangeId;
    
    private Integer           exchangeNumerator;
    
    private Integer           exchangeDenonumerator;
    
    private Integer           sts;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Long              operatorId;
    
    private Long              minOriMeaCnt;
    
    private Long              maxOriMeaCnt;
    
    public long getRuleId()
    {
        return this.ruleId;
    }
    
    public void setRuleId(long ruleId)
    {
        this.ruleId = ruleId;
    }
    
    public Long getMeasureId()
    {
        return this.measureId;
    }
    
    public void setMeasureId(Long measureId)
    {
        this.measureId = measureId;
    }
    
    public Long getDestMeasureId()
    {
        return this.destMeasureId;
    }
    
    public void setDestMeasureId(Long destMeasureId)
    {
        this.destMeasureId = destMeasureId;
    }
    
    public Long getMeasureExchangeId()
    {
        return this.measureExchangeId;
    }
    
    public void setMeasureExchangeId(Long measureExchangeId)
    {
        this.measureExchangeId = measureExchangeId;
    }
    
    public Integer getExchangeNumerator()
    {
        return this.exchangeNumerator;
    }
    
    public void setExchangeNumerator(Integer exchangeNumerator)
    {
        this.exchangeNumerator = exchangeNumerator;
    }
    
    public Integer getExchangeDenonumerator()
    {
        return this.exchangeDenonumerator;
    }
    
    public void setExchangeDenonumerator(Integer exchangeDenonumerator)
    {
        this.exchangeDenonumerator = exchangeDenonumerator;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public Long getMinOriMeaCnt()
    {
        return this.minOriMeaCnt;
    }
    
    public void setMinOriMeaCnt(Long minOriMeaCnt)
    {
        this.minOriMeaCnt = minOriMeaCnt;
    }
    
    public Long getMaxOriMeaCnt()
    {
        return this.maxOriMeaCnt;
    }
    
    public void setMaxOriMeaCnt(Long maxOriMeaCnt)
    {
        this.maxOriMeaCnt = maxOriMeaCnt;
    }
    
}
