package com.asiainfo.meo.system.common.app.model.entity;

// Generated 2015-3-25 16:30:00 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysMeasureDef generated by hbm2java
 */
public class SysMeasureDef implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID   = 1L;
    
    public static final Long  CURRENCY_UNIT_TYPE = (long) 0;
    
    public static final Long  TIME_UNIT_TYPE     = (long) 1;
    
    private long              measureId;
    
    private Long              measureTypeId;
    
    private String            name;
    
    private Integer           isDisplay;
    
    private String            description;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Long              operatorId;
    
    private Integer           sts;
    
    public long getMeasureId()
    {
        return measureId;
    }
    
    public void setMeasureId(long measureId)
    {
        this.measureId = measureId;
    }
    
    public Long getMeasureTypeId()
    {
        return measureTypeId;
    }
    
    public void setMeasureTypeId(Long measureTypeId)
    {
        this.measureTypeId = measureTypeId;
    }
    
    public String getName()
    {
        return name;
    }
    
    public void setName(String name)
    {
        this.name = name;
    }
    
    public Integer getIsDisplay()
    {
        return isDisplay;
    }
    
    public void setIsDisplay(Integer isDisplay)
    {
        this.isDisplay = isDisplay;
    }
    
    public String getDescription()
    {
        return description;
    }
    
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
}
