package com.asiainfo.meo.system.template.app.model.entity;

// Generated 2015-8-3 11:47:05 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysActionRecordTempleteRel generated by hbm2java
 */
public class SysActionRecordTempleteRel implements java.io.Serializable {

	private long relId;
	private Long actionId;
	private Long templateId;
	private Integer recordType;
	private Integer sts;
	private Timestamp createDate;
	private Timestamp modifyDate;

	public SysActionRecordTempleteRel() {
	}

	public SysActionRecordTempleteRel(long relId) {
		this.relId = relId;
	}

	public SysActionRecordTempleteRel(long relId, Long actionId,
			Long templateId, Integer recordType, Integer sts,
			Timestamp createDate, Timestamp modifyDate) {
		this.relId = relId;
		this.actionId = actionId;
		this.templateId = templateId;
		this.recordType = recordType;
		this.sts = sts;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public long getRelId() {
		return this.relId;
	}

	public void setRelId(long relId) {
		this.relId = relId;
	}

	public Long getActionId() {
		return this.actionId;
	}

	public void setActionId(Long actionId) {
		this.actionId = actionId;
	}

	public Long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	public Integer getRecordType() {
		return this.recordType;
	}

	public void setRecordType(Integer recordType) {
		this.recordType = recordType;
	}

	public Integer getSts() {
		return this.sts;
	}

	public void setSts(Integer sts) {
		this.sts = sts;
	}

	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	public Timestamp getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Timestamp modifyDate) {
		this.modifyDate = modifyDate;
	}

}
