package com.asiainfo.meo.system.template.app.model.entity;

// Generated 2015-7-31 18:27:27 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysMessageTemplateDef generated by hbm2java
 */
public class SysMessageTemplateDef implements java.io.Serializable
{
    
    private long                templateId;
    
    private String              templateName;
    
    private String              templateContent;
    
    private String              templateDesc;
    
    private Integer             sts;
    
    private Timestamp           createDate;
    
    private Timestamp           modifyDate;
    
    private Long                operatorId;
    
    public static final String  SEQ_SYS_MESSAGE_TEMPLATE = "SYS_MESSAGE_TEMPLATE_ID";
    
    public static final Integer STS_INVALID                 = 2;
    
    public static final Integer STS_VALID                   = 1;
    
    public long getTemplateId()
    {
        return this.templateId;
    }
    
    public void setTemplateId(long templateId)
    {
        this.templateId = templateId;
    }
    
    public String getTemplateName()
    {
        return this.templateName;
    }
    
    public void setTemplateName(String templateName)
    {
        this.templateName = templateName;
    }
    
    public String getTemplateContent()
    {
        return this.templateContent;
    }
    
    public void setTemplateContent(String templateContent)
    {
        this.templateContent = templateContent;
    }
    
    public String getTemplateDesc()
    {
        return this.templateDesc;
    }
    
    public void setTemplateDesc(String templateDesc)
    {
        this.templateDesc = templateDesc;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
}
