package com.asiainfo.meo.system.template.app.model.entity;

// Generated 2015-7-31 19:05:12 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysMessageTemplateParamRel generated by hbm2java
 */
public class SysMessageTemplateParamRel implements java.io.Serializable {

	private long tempParamRelId;
	private Long templateId;
	private Long patamId;
	private Integer sts;
	private Timestamp createDate;
	private Timestamp modifyDate;
	private Long operatorId;

	public SysMessageTemplateParamRel() {
	}

	public SysMessageTemplateParamRel(long tempParamRelId) {
		this.tempParamRelId = tempParamRelId;
	}

	public SysMessageTemplateParamRel(long tempParamRelId, Long templateId,
			Long patamId, Integer sts, Timestamp createDate,
			Timestamp modifyDate, Long operatorId) {
		this.tempParamRelId = tempParamRelId;
		this.templateId = templateId;
		this.patamId = patamId;
		this.sts = sts;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.operatorId = operatorId;
	}

	public long getTempParamRelId() {
		return this.tempParamRelId;
	}

	public void setTempParamRelId(long tempParamRelId) {
		this.tempParamRelId = tempParamRelId;
	}

	public Long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	public Long getPatamId() {
		return this.patamId;
	}

	public void setPatamId(Long patamId) {
		this.patamId = patamId;
	}

	public Integer getSts() {
		return this.sts;
	}

	public void setSts(Integer sts) {
		this.sts = sts;
	}

	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	public Timestamp getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Timestamp modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

}
