package com.asiainfo.meo.system.template.app.model.entity;

// Generated 2015-8-3 10:10:37 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysTemplateParamRule generated by hbm2java
 */
public class SysTemplateParamRule implements java.io.Serializable {

	public static final Integer STS_INVALID = 2;
    public static final Integer STS_VALID = 1;
    public static final Integer SCRIPT_TYPE_SQL = 1;
    private long ruleId;
	private Long paramId;
	private Integer ruleScriptType;
	private String scriptContext;
	private Integer sts;
	private Timestamp createDate;
	private Timestamp modifyDate;
	private Long operatorId;

	public SysTemplateParamRule() {
	}

	public SysTemplateParamRule(long ruleId) {
		this.ruleId = ruleId;
	}

	public SysTemplateParamRule(long ruleId, Long paramId,
			Integer ruleScriptType, String scriptContext, Integer sts,
			Timestamp createDate, Timestamp modifyDate, Long operatorId) {
		this.ruleId = ruleId;
		this.paramId = paramId;
		this.ruleScriptType = ruleScriptType;
		this.scriptContext = scriptContext;
		this.sts = sts;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.operatorId = operatorId;
	}

	public long getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(long ruleId) {
		this.ruleId = ruleId;
	}

	public Long getParamId() {
		return this.paramId;
	}

	public void setParamId(Long paramId) {
		this.paramId = paramId;
	}

	public Integer getRuleScriptType() {
		return this.ruleScriptType;
	}

	public void setRuleScriptType(Integer ruleScriptType) {
		this.ruleScriptType = ruleScriptType;
	}

	public String getScriptContext() {
		return this.scriptContext;
	}

	public void setScriptContext(String scriptContext) {
		this.scriptContext = scriptContext;
	}

	public Integer getSts() {
		return this.sts;
	}

	public void setSts(Integer sts) {
		this.sts = sts;
	}

	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	public Timestamp getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Timestamp modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

}
