package com.asiainfo.meo.system.template.app.model.entity;

// Generated 2015-7-31 18:27:27 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysTemplateParamDef generated by hbm2java
 */
public class SysTemplateParamDef implements java.io.Serializable
{
    
    public static final String  SEQ_SYS_TEMPLATE_PARAM = "SYS_TEMPLATE_PARAM_ID";
    
    private long                paramId;
    
    private String               paramName;
    
    private Integer             paramType;
    
    private String              paramDesc;
    
    private Integer             sts;
    
    private Timestamp           createDate;
    
    private Timestamp           modifyDate;
    
    private Long                operatorId;
    
    public static final Integer STS_INVALID            = 2;
    
    public static final Integer STS_VALID              = 1;
    
    public long getParamId()
    {
        return this.paramId;
    }
    
    public void setParamId(long paramId)
    {
        this.paramId = paramId;
    }
    
    public String getParamName()
    {
        return this.paramName;
    }
    
    public void setParamName(String paramName)
    {
        this.paramName = paramName;
    }
    
    public Integer getParamType()
    {
        return this.paramType;
    }
    
    public void setParamType(Integer paramType)
    {
        this.paramType = paramType;
    }
    
    public String getParamDesc()
    {
        return this.paramDesc;
    }
    
    public void setParamDesc(String paramDesc)
    {
        this.paramDesc = paramDesc;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
}
