package com.asiainfo.meo.product.profile.app.model.vo;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

/**
 * CmPrice generated by hbm2java
 */
public class PriceVO implements java.io.Serializable
{
    
    private Long    priceId;
    
    private String  priceName;
    
    private Long    price;
    
    private Integer priceUnit;
    
    private String  unit;
    
    private Integer priceType;
    
    private String  type;
    
    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    public Long getPriceId()
    {
        return priceId;
    }
    
    public void setPriceId(Long priceId)
    {
        this.priceId = priceId;
    }
    
    public String getPriceName()
    {
        return priceName;
    }
    
    public void setPriceName(String priceName)
    {
        this.priceName = priceName;
    }
    
    public Long getPrice()
    {
        return price;
    }
    
    public void setPrice(Long price)
    {
        this.price = price;
    }
    
    public Integer getPriceUnit()
    {
        return priceUnit;
    }
    
    public void setPriceUnit(Integer priceUnit)
    {
        this.priceUnit = priceUnit;
    }
    
    public String getUnit()
    {
        return unit;
    }
    
    public void setUnit(String unit)
    {
        this.unit = unit;
    }
    
    public Integer getPriceType()
    {
        return priceType;
    }
    
    public void setPriceType(Integer priceType)
    {
        this.priceType = priceType;
    }
    
}
