package com.asiainfo.meo.web.notification.model.vo;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.asiainfo.meo.common.core.validate.group.Insert;
import com.asiainfo.meo.common.core.validate.group.Update;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

/**
 * SysNotificationDef generated by hbm2java
 */
public class UINotificationDefVO implements java.io.Serializable
{
    
    @Valid
    @NotNull(groups={Update.class})
    private Long    notifyId;
    
    @Valid
    @NotNull(groups={Insert.class, Update.class})
    private Long    templateId;
    
    private String  templateName;
    
    @Valid
    @NotEmpty(groups={Insert.class, Update.class})
    private String  notificationName;
    
    private String  notificationDesc;
    
    private Long    operatorId;
    
    @Valid
    @NotNull(groups={Insert.class, Update.class})
    private Integer notifTypeId;
    
    private String  notifType;

    public Long getNotifyId()
    {
        return notifyId;
    }

    public void setNotifyId(Long notifyId)
    {
        this.notifyId = notifyId;
    }

    public Long getTemplateId()
    {
        return templateId;
    }

    public void setTemplateId(Long templateId)
    {
        this.templateId = templateId;
    }

    public String getTemplateName()
    {
        return templateName;
    }

    public void setTemplateName(String templateName)
    {
        this.templateName = templateName;
    }

    public String getNotificationName()
    {
        return notificationName;
    }

    public void setNotificationName(String notificationName)
    {
        this.notificationName = notificationName;
    }

    public String getNotificationDesc()
    {
        return notificationDesc;
    }

    public void setNotificationDesc(String notificationDesc)
    {
        this.notificationDesc = notificationDesc;
    }

    public Long getOperatorId()
    {
        return operatorId;
    }

    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }

    public Integer getNotifTypeId()
    {
        return notifTypeId;
    }

    public void setNotifTypeId(Integer notifTypeId)
    {
        this.notifTypeId = notifTypeId;
    }

    public String getNotifType()
    {
        return notifType;
    }

    public void setNotifType(String notifType)
    {
        this.notifType = notifType;
    }

}
