package com.asiainfo.meo.prm.file.app.model.entity;

// Generated 2015-4-9 13:11:57 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.asiainfo.meo.common.core.validate.group.Insert;
import com.asiainfo.meo.common.core.validate.group.Update;

/**
 * CmFileInfo generated by hbm2java
 */
public class PartnerFileInfo implements java.io.Serializable {

    private static final long serialVersionUID = 7758277525263662106L;
    
    public static final int STS_VALID=0;
    
    public static final int STS_INVALID=1;
    
    public static final  int FILE_TYPE_AVATAR=0;
    
    public static final  int FILE_TYPE_REGISTRATION_FORM=1;
    
    private long fileId;
    @NotEmpty(groups={Insert.class,Update.class})
	private String fileName;
    @NotEmpty(groups={Insert.class,Update.class})
	private String fileUrl;
	private Timestamp createDate;
	private Timestamp modifyDate;
	private Integer sts;
	@NotNull(groups={Insert.class,Update.class})
	private Integer fileType;
	private Long fileSize;
	@NotNull(groups={Insert.class,Update.class})
	private Long partnerId;

	public PartnerFileInfo() {
	}

	public PartnerFileInfo(long fileId, String fileName, String fileUrl,
			Timestamp modifyDate) {
		this.fileId = fileId;
		this.fileName = fileName;
		this.fileUrl = fileUrl;
		this.modifyDate = modifyDate;
	}

	public PartnerFileInfo(long fileId, String fileName, String fileUrl,
			Timestamp createDate, Timestamp modifyDate, Integer sts,
			Integer fileType, Long fileSize, Long partnerId) {
		this.fileId = fileId;
		this.fileName = fileName;
		this.fileUrl = fileUrl;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.sts = sts;
		this.fileType = fileType;
		this.fileSize = fileSize;
		this.partnerId = partnerId;
	}

	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	public Timestamp getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Timestamp modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getSts() {
		return this.sts;
	}

	public void setSts(Integer sts) {
		this.sts = sts;
	}

	public Integer getFileType() {
		return this.fileType;
	}

	public void setFileType(Integer fileType) {
		this.fileType = fileType;
	}

	public Long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	public Long getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(Long partnerId) {
		this.partnerId = partnerId;
	}

}
