package com.asiainfo.meo.web.product.model.vo;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.asiainfo.meo.common.core.validate.group.Insert;
import com.asiainfo.meo.common.core.validate.group.Update;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1


/**
 * CmPrice generated by hbm2java
 */
public class UIPriceVO implements java.io.Serializable
{
    @Valid
    @NotNull(groups={Update.class})
    private Long    priceId;
    
    @Valid
    @NotEmpty(groups={Insert.class, Update.class})
    private String  priceName;
    
    @Valid
    @NotNull(groups={Insert.class, Update.class})
    private Long    price;
    
    private Integer priceUnit;
    
    private String  unit;
    
    private Integer priceType;
    
    private String  type;
    
    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    public String getUnit()
    {
        return unit;
    }

    public void setUnit(String unit)
    {
        this.unit = unit;
    }

    public Long getPrice()
    {
        return price;
    }
    
    public void setPrice(Long price)
    {
        this.price = price;
    }
    
    public Long getPriceId()
    {
        return priceId;
    }

    public void setPriceId(Long priceId)
    {
        this.priceId = priceId;
    }

    public String getPriceName()
    {
        return priceName;
    }
    
    public void setPriceName(String priceName)
    {
        this.priceName = priceName;
    }
    
    public Integer getPriceUnit()
    {
        return priceUnit;
    }
    
    public void setPriceUnit(Integer priceUnit)
    {
        this.priceUnit = priceUnit;
    }
    
    public Integer getPriceType()
    {
        return priceType;
    }
    
    public void setPriceType(Integer priceType)
    {
        this.priceType = priceType;
    }
    
}
