package com.asiainfo.meo.system.authority.app.model.vo;

// Generated 2015-4-3 16:25:17 by Hibernate Tools 3.4.0.CR1


/**
 * SysOperater generated by hbm2java
 */
public class UserOperaterVO
{
    
    private long      operId;
    
    private String    operName;
    
    
    public long getOperId()
    {
        return this.operId;
    }
    
    public void setOperId(long operId)
    {
        this.operId = operId;
    }
    
    public String getOperName()
    {
        return this.operName;
    }
    
    public void setOperName(String operName)
    {
        this.operName = operName;
    }
    
    
}
