package com.asiainfo.meo.system.authority.app.model.vo;

// Generated 2015-4-3 16:25:17 by Hibernate Tools 3.4.0.CR1


/**
 * SysMenu generated by hbm2java
 */
public class UserMenuVO implements java.io.Serializable
{
    
    private Long   menuId;
    
    private String menuName;
    
    private Long   parentMenuId;
    
    private String url;
    
    private Long   systemId;
    
    private String systemValue;
    
    private Long   moduleId;
    
    private String moduleValue;
    
    private String imagUrl;
    
    private Integer menuType;

    public String getSystemValue()
    {
        return systemValue;
    }

    public void setSystemValue(String systemValue)
    {
        this.systemValue = systemValue;
    }

    public String getModuleValue()
    {
        return moduleValue;
    }

    public void setModuleValue(String moduleValue)
    {
        this.moduleValue = moduleValue;
    }

    public Integer getMenuType()
    {
        return menuType;
    }

    public void setMenuType(Integer menuType)
    {
        this.menuType = menuType;
    }

    public Long getMenuId()
    {
        return menuId;
    }

    public void setMenuId(Long menuId)
    {
        this.menuId = menuId;
    }

    public String getMenuName()
    {
        return menuName;
    }

    public void setMenuName(String menuName)
    {
        this.menuName = menuName;
    }

    public Long getParentMenuId()
    {
        return parentMenuId;
    }

    public void setParentMenuId(Long parentMenuId)
    {
        this.parentMenuId = parentMenuId;
    }

    public String getUrl()
    {
        return url;
    }

    public void setUrl(String url)
    {
        this.url = url;
    }

    public Long getSystemId()
    {
        return systemId;
    }

    public void setSystemId(Long systemId)
    {
        this.systemId = systemId;
    }

    public Long getModuleId()
    {
        return moduleId;
    }

    public void setModuleId(Long moduleId)
    {
        this.moduleId = moduleId;
    }

    public String getImagUrl()
    {
        return imagUrl;
    }

    public void setImagUrl(String imagUrl)
    {
        this.imagUrl = imagUrl;
    }
    
   
}
