package com.asiainfo.meo.customer.asset.app.model.entity;

// default package
// Generated 2015-3-2 16:45:59 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmAssetChgDetail generated by hbm2java
 */
public class AssetChgDetail implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 7766149839347645161L;
    
    private long              id;
    
    private Long              assetId;
    
    private Long              custId;
    
    private Integer           assetType;
    
    private Long              amount;
    
    //private Long              busiCode;
    
    private Timestamp         doneTime;
    
    //private Long              soNbr;
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public Long getAssetId()
    {
        return this.assetId;
    }
    
    public void setAssetId(Long assetId)
    {
        this.assetId = assetId;
    }
    
    public Long getCustId()
    {
        return this.custId;
    }
    
    public void setCustId(Long custId)
    {
        this.custId = custId;
    }
    
    public Integer getAssetType()
    {
        return this.assetType;
    }
    
    public void setAssetType(Integer assetType)
    {
        this.assetType = assetType;
    }
    
    public Long getAmount()
    {
        return this.amount;
    }
    
    public void setAmount(Long amount)
    {
        this.amount = amount;
    }
    
    //public Long getBusiCode()
    //{
    //    return this.busiCode;
    //}
    
    //public void setBusiCode(Long busiCode)
    //{
    //    this.busiCode = busiCode;
    //}
    
    public Timestamp getDoneTime()
    {
        return this.doneTime;
    }
    
    public void setDoneTime(Timestamp doneTime)
    {
        this.doneTime = doneTime;
    }
    
    //public Long getSoNbr()
    //{
    //    return this.soNbr;
    //}
    
    //public void setSoNbr(Long soNbr)
    //{
    //    this.soNbr = soNbr;
    //}
    
}
