package com.asiainfo.meo.customer.asset.app.model.entity;

// Generated 2015-3-2 16:43:54 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;

import com.asiainfo.meo.common.core.validate.group.Insert;
import com.asiainfo.meo.common.core.validate.group.Update;

/**
 * CmAsset generated by hbm2java
 */
public class Asset implements java.io.Serializable
{
    
    
    /**
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么)
    */ 
    private static final long serialVersionUID = -314768562624930231L;
    private long                assetId;
    @NotNull(groups={Update.class , Insert.class})
    private int                 assetType;
    @NotNull(groups={Update.class , Insert.class})
    private long                amount;
    @NotNull(groups=Insert.class)
    private Timestamp           createDate;
    
    private Timestamp           modifyDate;
    @NotNull(groups={Update.class , Insert.class})
    private long                custId;
    
    private Integer             unit;
    
    private Integer           sts;
    
    public static final Integer ASSET_TYPE_EXPERIENCE   = 1;
    
    public static final Integer ASSET_TYPE_COINS        = 2;
    
    public static final Integer ASSET_TYPE_PERIOD_COINS = 3;
    
    public static final Integer ASSET_TYPE_TOTAL_COINS  = 4;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getAssetId()
    {
        return this.assetId;
    }
    
    public void setAssetId(long assetId)
    {
        this.assetId = assetId;
    }
    
    public int getAssetType()
    {
        return this.assetType;
    }
    
    public void setAssetType(int assetType)
    {
        this.assetType = assetType;
    }
    
    public long getAmount()
    {
        return this.amount;
    }
    
    public void setAmount(long amount)
    {
        this.amount = amount;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public long getCustId()
    {
        return this.custId;
    }
    
    public void setCustId(long custId)
    {
        this.custId = custId;
    }
    
    public Integer getUnit()
    {
        return this.unit;
    }
    
    public void setUnit(Integer unit)
    {
        this.unit = unit;
    }

    public Integer getSts()
    {
        return sts;
    }

    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
}
