package com.asiainfo.meo.meo.notification.configuration.model.entity;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * SysNotificationDef generated by hbm2java
 */
public class SysNotificationDef implements java.io.Serializable
{
    
    private long                notifyId;
    
    private Long                templateId;
    
    private String              notifName;
    
    private String              notifDesc;
    
    private Integer             sts;
    
    private Timestamp           createDate;
    
    private Timestamp           modifyDate;
    
    private Long                operator;
    
    private Integer             notifType;
    
    public static final String  SEQ_SYS_NOTIFICATION_DEF = "SYS_NOTIFICATION_ID";
    
    public static final Integer STS_VALID                = 1;
    
    public static final Integer STS_INVALID              = 2;
    
    public static final Integer SYSTEM_NOTIFICATION      = 1;
    
    public static final Integer USER_NOTIFICATION        = 2;
    
    public long getNotifyId()
    {
        return notifyId;
    }
    
    public void setNotifyId(long notifyId)
    {
        this.notifyId = notifyId;
    }
    
    public Long getTemplateId()
    {
        return this.templateId;
    }
    
    public void setTemplateId(Long templateId)
    {
        this.templateId = templateId;
    }
    
    public String getNotifName()
    {
        return this.notifName;
    }
    
    public void setNotifName(String notifName)
    {
        this.notifName = notifName;
    }
    
    public String getNotifDesc()
    {
        return this.notifDesc;
    }
    
    public void setNotifDesc(String notifDesc)
    {
        this.notifDesc = notifDesc;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getOperator()
    {
        return this.operator;
    }
    
    public void setOperator(Long operator)
    {
        this.operator = operator;
    }
    
    public Integer getNotifType()
    {
        return notifType;
    }
    
    public void setNotifType(Integer notifType)
    {
        this.notifType = notifType;
    }
    
}
