package com.asiainfo.meo.web.common.define.model.vo;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

// Generated 2015-3-25 16:30:00 by Hibernate Tools 3.4.0.CR1


/**
 * SysCategoryDef generated by hbm2java
 */
public class UICategoryDefVO implements java.io.Serializable
{
    /**                                                                           
      * @Fields serialVersionUID : (用一句话描述这个变量表示什么)                                                                                                                                                                                                                                  
      */
    private static final long serialVersionUID = 1L;

    @Valid
    @NotEmpty
    private String              name;
    
    @Valid
    @NotNull
    private Long                categoryId;
    
    private String              description;

    private Long                operatorId;
    
    private Long                parentCateId;
    
    public Long getCategoryId()
    {
        return categoryId;
    }

    public void setCategoryId(Long categoryId)
    {
        this.categoryId = categoryId;
    }

    public String getName()
    {
        return this.name;
    }
    
    public void setName(String name)
    {
        this.name = name;
    }
    
    public String getDescription()
    {
        return this.description;
    }
    
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public Long getParentCateId()
    {
        return this.parentCateId;
    }
    
    public void setParentCateId(Long parentCateId)
    {
        this.parentCateId = parentCateId;
    }
    
}
