package com.asiainfo.meo.campaign.profile.app.model.entity;

// Generated 2015-5-11 19:31:42 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaign generated by hbm2java
 */
public class Campaign implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 1L;
    
    public static final int   STS_DRAF         = 0;
    
    public static final int   STS_PUBLISHED    = 1;
    
    public static final int   STS_ACTIVE       = 2;
    
    public static final int   STS_SUSPENDED    = 3;
    
    public static final int   STS_RENEW        = 4;
    
    public static final int   STS_EXPIRED      = 5;
    
    public static final int   STS_COMPLETED    = 6;
    
    public static final int   STS_TERMINATED   = 7;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public static final int   STS_ISEDIT       = 0;
    
    public static final int   STS_UNEDIT       = 1;
    
    private long              campaignId;
    
    private String            campaignNo;
    
    private String            campaignName;
    
    private Integer           campaignType;
    
    private Timestamp         campaignBeginDate;
    
    private Timestamp         campaignEndDate;
    
    private Long              agreementId;
    // STS代表本条数据的状态
    private Integer           sts;
    
    private String            iconUrl;
    
    private Timestamp         validDate;
    
    private Timestamp         expiredDate;
    
    private Integer           categoryId;
    
    private String            description;
    
    private Long              partnerId;
    
    private Integer           participant;
    
    private Long              operatorId;
    //campaign_sts业务状态
    private Integer           campaignSts;
    
    private String            campaignUrl;
    
    private Integer           isEdit;
    
    private String version;
    
    public long getCampaignId()
    {
        return this.campaignId;
    }
    
    public void setCampaignId(long campaignId)
    {
        this.campaignId = campaignId;
    }
    
    public String getCampaignNo()
    {
        return this.campaignNo;
    }
    
    public void setCampaignNo(String campaignNo)
    {
        this.campaignNo = campaignNo;
    }
    
    public String getCampaignName()
    {
        return this.campaignName;
    }
    
    public void setCampaignName(String campaignName)
    {
        this.campaignName = campaignName;
    }
    
    public Integer getCampaignType()
    {
        return this.campaignType;
    }
    
    public void setCampaignType(Integer campaignType)
    {
        this.campaignType = campaignType;
    }
    
    public Timestamp getCampaignBeginDate()
    {
        return this.campaignBeginDate;
    }
    
    public void setCampaignBeginDate(Timestamp campaignBeginDate)
    {
        this.campaignBeginDate = campaignBeginDate;
    }
    
    public Timestamp getCampaignEndDate()
    {
        return this.campaignEndDate;
    }
    
    public void setCampaignEndDate(Timestamp campaignEndDate)
    {
        this.campaignEndDate = campaignEndDate;
    }
    
    public Long getAgreementId()
    {
        return this.agreementId;
    }
    
    public void setAgreementId(Long agreementId)
    {
        this.agreementId = agreementId;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public String getIconUrl()
    {
        return this.iconUrl;
    }
    
    public void setIconUrl(String iconUrl)
    {
        this.iconUrl = iconUrl;
    }
    
    public Timestamp getValidDate()
    {
        return this.validDate;
    }
    
    public void setValidDate(Timestamp validDate)
    {
        this.validDate = validDate;
    }
    
    public Timestamp getExpiredDate()
    {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Timestamp expiredDate)
    {
        this.expiredDate = expiredDate;
    }
    
    public Integer getCategoryId()
    {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId)
    {
        this.categoryId = categoryId;
    }
    
    public String getDescription()
    {
        return this.description;
    }
    
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    public Long getPartnerId()
    {
        return this.partnerId;
    }
    
    public void setPartnerId(Long partnerId)
    {
        this.partnerId = partnerId;
    }
    
    public Integer getParticipant()
    {
        return participant;
    }

    public void setParticipant(Integer participant)
    {
        this.participant = participant;
    }

    public Long getOperatorId()
    {
        return this.operatorId;
    }
    
    public void setOperatorId(Long operatorId)
    {
        this.operatorId = operatorId;
    }
    
    public Integer getCampaignSts()
    {
        return this.campaignSts;
    }
    
    public void setCampaignSts(Integer campaignSts)
    {
        this.campaignSts = campaignSts;
    }
    
    public String getCampaignUrl()
    {
        return this.campaignUrl;
    }
    
    public void setCampaignUrl(String campaignUrl)
    {
        this.campaignUrl = campaignUrl;
    }
    
    public Integer getIsEdit()
    {
        return this.isEdit;
    }
    
    public void setIsEdit(Integer isEdit)
    {
        this.isEdit = isEdit;
    }
    
    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }
}
