package com.asiainfo.meo.campaign.profile.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaignProperty generated by hbm2java
 */
public class CampaignProperty implements java.io.Serializable
{
    private static final long serialVersionUID = 4407583642153939166L;
    
    private long              propertyId;
    
    private long              propertyKey;
    
    private String            propertyValue;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Long              campaignId;
    
    private Integer           sts;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getPropertyId()
    {
        return propertyId;
    }
    
    public void setPropertyId(long propertyId)
    {
        this.propertyId = propertyId;
    }
    
    public long getPropertyKey()
    {
        return propertyKey;
    }
    
    public void setPropertyKey(long propertyKey)
    {
        this.propertyKey = propertyKey;
    }
    
    public String getPropertyValue()
    {
        return this.propertyValue;
    }
    
    public void setPropertyValue(String propertyValue)
    {
        this.propertyValue = propertyValue;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getCampaignId()
    {
        return campaignId;
    }
    
    public void setCampaignId(Long campaignId)
    {
        this.campaignId = campaignId;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
}
