package com.asiainfo.meo.campaign.profile.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaignPropertyDef generated by hbm2java
 */
public class CampaignPropertyDef implements java.io.Serializable
{
    private static final long serialVersionUID = -6567199346053875509L;
    
    private long              propertyKey;
    
    private String            propertyCode;
    
    private String            propertyName;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Integer           sts;
    
    private int               mandatory;
    
    private int               campaignType;
    
    private Integer           propertyValueType;
    //必填
    public static int         IS_MANDATORY = 0;
    //非必填
    public static int         UN_MANDATORY = 1;
    
    public static final int   STS_VALID        = 1;
    
    public static final int   STS_INVALID      = 2;
    
    public long getPropertyKey()
    {
        return propertyKey;
    }
    
    public void setPropertyKey(long propertyKey)
    {
        this.propertyKey = propertyKey;
    }
    
    public String getPropertyCode()
    {
        return propertyCode;
    }
    
    public void setPropertyCode(String propertyCode)
    {
        this.propertyCode = propertyCode;
    }
    
    public String getPropertyName()
    {
        return propertyName;
    }
    
    public void setPropertyName(String propertyName)
    {
        this.propertyName = propertyName;
    }
    
    public Timestamp getCreateDate()
    {
        return createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public int getMandatory()
    {
        return mandatory;
    }
    
    public void setMandatory(int mandatory)
    {
        this.mandatory = mandatory;
    }
    
    public int getCampaignType()
    {
        return campaignType;
    }
    
    public void setCampaignType(int campaignType)
    {
        this.campaignType = campaignType;
    }

    public Integer getPropertyValueType()
    {
        return propertyValueType;
    }

    public void setPropertyValueType(Integer propertyValueType)
    {
        this.propertyValueType = propertyValueType;
    }
}
