package com.asiainfo.meo.campaign.profile.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaignComment generated by hbm2java
 */
public class CampaignComment implements java.io.Serializable
{
    private static final long serialVersionUID = 2029566745383380237L;
    
    private long              id;
    
    private Long              custId;
    
    private Integer           star;
    
    private String            comment;
    
    private Integer           isLike;
    
    private Integer           shareChannel;
    
    private Timestamp         doneTime;
    
    private String            campaignNo;
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public Long getCustId()
    {
        return this.custId;
    }
    
    public void setCustId(Long custId)
    {
        this.custId = custId;
    }
    
    public Integer getStar()
    {
        return this.star;
    }
    
    public void setStar(Integer star)
    {
        this.star = star;
    }
    
    public String getComment()
    {
        return this.comment;
    }
    
    public void setComment(String comment)
    {
        this.comment = comment;
    }
    
    public Integer getIsLike()
    {
        return this.isLike;
    }
    
    public void setIsLike(Integer isLike)
    {
        this.isLike = isLike;
    }
    
    public Integer getShareChannel()
    {
        return this.shareChannel;
    }
    
    public void setShareChannel(Integer shareChannel)
    {
        this.shareChannel = shareChannel;
    }
    
    public Timestamp getDoneTime()
    {
        return this.doneTime;
    }
    
    public void setDoneTime(Timestamp doneTime)
    {
        this.doneTime = doneTime;
    }
    
    public String getCampaignNo()
    {
        return this.campaignNo;
    }
    
    public void setCampaignNo(String campaignNo)
    {
        this.campaignNo = campaignNo;
    }
    
}
