package com.asiainfo.meo.campaign.profile.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmCampaignActivitySummary generated by hbm2java
 */
public class CampaignActivitySummary implements java.io.Serializable
{
    
    private static final long serialVersionUID = 804740671235377372L;
    
    public static final Integer PARTICIPANT_TYPE = 2;
    
    private long              id;
    
    private Long              actionId;
    
    private Integer           summaryType;
    
    private Long              summaryValue;
    
    private Timestamp         createDate;
    
    private Timestamp         modifyDate;
    
    private Integer           sts;
    
    private String            campaignNo;
    
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public Long getActionId()
    {
        return this.actionId;
    }
    
    public void setActionId(Long actionId)
    {
        this.actionId = actionId;
    }
    
    public Integer getSummaryType()
    {
        return this.summaryType;
    }
    
    public void setSummaryType(Integer summaryType)
    {
        this.summaryType = summaryType;
    }
    
    public Long getSummaryValue()
    {
        return this.summaryValue;
    }
    
    public void setSummaryValue(Long summaryValue)
    {
        this.summaryValue = summaryValue;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Integer getSts()
    {
        return this.sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public String getCampaignNo()
    {
        return this.campaignNo;
    }
    
    public void setCampaignNo(String campaignNo)
    {
        this.campaignNo = campaignNo;
    }
    
}
