package com.asiainfo.meo.campaign.profile.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmRewardActivity generated by hbm2java
 */
public class RewardActivity implements java.io.Serializable
{
    private static final long serialVersionUID = 5859866129796917989L;
    
    private long              rewardId;
    
    private Long              activityId;
    
    private String            campaignNo;
    
    private Long              custId;
    
    private Timestamp         doneTime;
    
    private Integer           rewardType;
    
    private Integer           rewardValue;
    
    private Integer           rewardUnit;
    
    private Long              actionId;
    
    private Long              taskId;
    
    public long getRewardId()
    {
        return this.rewardId;
    }
    
    public void setRewardId(long rewardId)
    {
        this.rewardId = rewardId;
    }
    
    public Long getActivityId()
    {
        return this.activityId;
    }
    
    public void setActivityId(Long activityId)
    {
        this.activityId = activityId;
    }
    
    public String getCampaignNo()
    {
        return this.campaignNo;
    }
    
    public void setCampaignNo(String campaignNo)
    {
        this.campaignNo = campaignNo;
    }
    
    public Long getCustId()
    {
        return this.custId;
    }
    
    public void setCustId(Long custId)
    {
        this.custId = custId;
    }
    
    public Timestamp getDoneTime()
    {
        return this.doneTime;
    }
    
    public void setDoneTime(Timestamp doneTime)
    {
        this.doneTime = doneTime;
    }
    
    public Integer getRewardType()
    {
        return this.rewardType;
    }
    
    public void setRewardType(Integer rewardType)
    {
        this.rewardType = rewardType;
    }
    
    public Integer getRewardValue()
    {
        return this.rewardValue;
    }
    
    public void setRewardValue(Integer rewardValue)
    {
        this.rewardValue = rewardValue;
    }
    
    public Integer getRewardUnit()
    {
        return this.rewardUnit;
    }
    
    public void setRewardUnit(Integer rewardUnit)
    {
        this.rewardUnit = rewardUnit;
    }
    
    public Long getActionId()
    {
        return this.actionId;
    }
    
    public void setActionId(Long actionId)
    {
        this.actionId = actionId;
    }
    
    public Long getTaskId()
    {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId)
    {
        this.taskId = taskId;
    }
    
}
