package com.asiainfo.meo.prm.contract.app.model.entity;

// Generated 2015-3-13 16:06:08 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmContractPriceRel generated by hbm2java
 */
public class ContractPriceRel implements java.io.Serializable
{
    private static final long serialVersionUID = -8177592550607555442L;
    
    /** price status constant */
    public static final int   STS_VALID        = 1;
    /** price status constant */
    public static final int   STS_INVALID      = 2;
    
    private long              id;
    
    private long              priceId;
    
    private long              contractId;
    
    private Timestamp         validDate;
    
    private Timestamp         expiredDate;
    
 //   @Enum(groups={Insert.class,Update.class},value={""+STS_VALID,""+STS_INVALID},message=PartnerContractErrorConstant.CONTRACT_PRICE_REL_STATUS_IS_ERROR)
    private int               sts;
    
    private Timestamp         modifyDate;
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public long getPriceId()
    {
        return this.priceId;
    }
    
    public void setPriceId(long priceId)
    {
        this.priceId = priceId;
    }
    
    public long getContractId()
    {
        return this.contractId;
    }
    
    public void setContractId(long contractId)
    {
        this.contractId = contractId;
    }
    
    public Timestamp getValidDate()
    {
        return this.validDate;
    }
    
    public void setValidDate(Timestamp validDate)
    {
        this.validDate = validDate;
    }
    
    public Timestamp getExpiredDate()
    {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Timestamp expiredDate)
    {
        this.expiredDate = expiredDate;
    }
    
    public int getSts()
    {
        return this.sts;
    }
    
    public void setSts(int sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    /**
     * @Description: TODO(contract price status is right or error)
     * @return
     */
    public boolean isStatus()
    {
        return isInvalidSts()|| isValidSts();
    }
    
    public boolean isValidSts()
    {
        return getSts()== STS_VALID;
    }
    
    public boolean isInvalidSts()
    {
        return getSts()== STS_INVALID;
    }
}
