package com.asiainfo.meo.prm.contract.app.model.entity;

// Generated 2015-4-20 14:45:47 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CmPrice generated by hbm2java
 */
public class Price implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (鐢ㄤ竴鍙ヨ瘽鎻忚堪杩欎釜鍙橀噺琛ㄧず浠�箞)
     */
    private static final long serialVersionUID        = 1L;
    
    private long              priceId;
    
    private Long              unitPrice;
    
    private Integer           unit;
    
    private Long              discountId;
    
    private Integer           priceType;
    
    private Integer           sts;
    
    private Timestamp         validDate;
    
    private Timestamp         expiredDate;
    
    private Timestamp         modifyDate;
    
    private Integer           chargeUnit;
    
    /** price type constant */
    public static final int   PRICE_TYPE_COIN         = 1;
    
    /** price type constant */
    public static final int   PRICE_TYPE_DATA_PACKAGE = 2;
    
    /** price status constant */
    public static final int   STS_VALID               = 1;
    
    /** price status constant */
    public static final int   STS_INVALID             = 2;
    
    public long getPriceId()
    {
        return priceId;
    }
    
    public void setPriceId(long priceId)
    {
        this.priceId = priceId;
    }
    
    public Long getUnitPrice()
    {
        return unitPrice;
    }
    
    public void setUnitPrice(Long unitPrice)
    {
        this.unitPrice = unitPrice;
    }
    
    public Integer getUnit()
    {
        return unit;
    }
    
    public void setUnit(Integer unit)
    {
        this.unit = unit;
    }
    
    public Long getDiscountId()
    {
        return discountId;
    }
    
    public void setDiscountId(Long discountId)
    {
        this.discountId = discountId;
    }
    
    public Integer getPriceType()
    {
        return priceType;
    }
    
    public void setPriceType(Integer priceType)
    {
        this.priceType = priceType;
    }
    
    public Integer getSts()
    {
        return sts;
    }
    
    public void setSts(Integer sts)
    {
        this.sts = sts;
    }
    
    public Timestamp getValidDate()
    {
        return validDate;
    }
    
    public void setValidDate(Timestamp validDate)
    {
        this.validDate = validDate;
    }
    
    public Timestamp getExpiredDate()
    {
        return expiredDate;
    }
    
    public void setExpiredDate(Timestamp expiredDate)
    {
        this.expiredDate = expiredDate;
    }
    
    public Timestamp getModifyDate()
    {
        return modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Integer getChargeUnit()
    {
        return chargeUnit;
    }
    
    public void setChargeUnit(Integer chargeUnit)
    {
        this.chargeUnit = chargeUnit;
    }
    
}
