package com.asiainfo.meo.customer.social.app.model.entity;

// Generated 2015-3-2 16:29:27 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.asiainfo.meo.common.core.validate.group.Insert;
import com.asiainfo.meo.common.core.validate.group.Update;

/**
 * CmSocialInfo generated by hbm2java
 */
public class SocialInfo implements java.io.Serializable
{
    
    /**
     * @Fields serialVersionUID : (用一句话描述这个变量表示什么)
     */
    private static final long serialVersionUID = 8009021842206053667L;
    private long              id;
    @NotEmpty(groups = {Update.class, Insert.class })
    private String            socialNumber;
    @NotNull(groups = {Update.class, Insert.class })
    private int               channel;
    @NotEmpty(groups = {Update.class, Insert.class })
    private String            msisdn;
    private String            emailAddr;
    private Integer           countryCode;
    private Integer           gender;
    private Date              birthday;
    private Integer           languageCode;
    private Integer           cityCode;
    private Integer           provinceCode;
    private Timestamp         createDate;
    private Timestamp         modifyDate;
    private Long              custId;
    
    public long getId()
    {
        return this.id;
    }
    
    public void setId(long id)
    {
        this.id = id;
    }
    
    public String getSocialNumber()
    {
        return this.socialNumber;
    }
    
    public void setSocialNumber(String socialNumber)
    {
        this.socialNumber = socialNumber;
    }
    
    public int getChannel()
    {
        return this.channel;
    }
    
    public void setChannel(int channel)
    {
        this.channel = channel;
    }
    
    public String getMsisdn()
    {
        return this.msisdn;
    }
    
    public void setMsisdn(String msisdn)
    {
        this.msisdn = msisdn;
    }
    
    public String getEmailAddr()
    {
        return this.emailAddr;
    }
    
    public void setEmailAddr(String emailAddr)
    {
        this.emailAddr = emailAddr;
    }
    
    public Integer getCountryCode()
    {
        return this.countryCode;
    }
    
    public void setCountryCode(Integer countryCode)
    {
        this.countryCode = countryCode;
    }
    
    public Integer getGender()
    {
        return this.gender;
    }
    
    public void setGender(Integer gender)
    {
        this.gender = gender;
    }
    
    public Integer getLanguageCode()
    {
        return this.languageCode;
    }
    
    public void setLanguageCode(Integer languageCode)
    {
        this.languageCode = languageCode;
    }
    
    public Integer getCityCode()
    {
        return this.cityCode;
    }
    
    public void setCityCode(Integer cityCode)
    {
        this.cityCode = cityCode;
    }
    
    public Integer getProvinceCode()
    {
        return this.provinceCode;
    }
    
    public void setProvinceCode(Integer provinceCode)
    {
        this.provinceCode = provinceCode;
    }
    
    public Timestamp getCreateDate()
    {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate)
    {
        this.createDate = createDate;
    }
    
    public Timestamp getModifyDate()
    {
        return this.modifyDate;
    }
    
    public void setModifyDate(Timestamp modifyDate)
    {
        this.modifyDate = modifyDate;
    }
    
    public Long getCustId()
    {
        return this.custId;
    }
    
    public void setCustId(Long custId)
    {
        this.custId = custId;
    }
    
    public void setBirthday(Date birthday)
    {
        this.birthday = birthday;
    }
    
    public Date getBirthday()
    {
        return birthday;
    }
    
}
